### ISSUE TITLE
License

### ISSUE THREAD

**Issue by tamaramagdr** [hbouvier/dns#11]
Hi, thanks for sharing your code! I could not find a license - any chance you would include one (e.g. MIT)?

**Comment by mathieukempe** [comment]
Same here we can't find the license for this project. Can it be added?

**Comment by efrecon** [comment]
Since I have sent a PR that got accepted, I just wanted to let you know that I am open to any kind of license that @hbouvier would choose. MIT or similar, or even BSD.

**Comment by mathieukempe** [comment]
MIT would be good, anything other than no license

**Comment by hbouvier** [comment]
I've added an MIT license.
